<!DOCTYPE html>
<html lang="en"><head>
<script src="session910_files/libs/clipboard/clipboard.min.js"></script>
<script src="session910_files/libs/quarto-html/tabby.min.js"></script>
<script src="session910_files/libs/quarto-html/popper.min.js"></script>
<script src="session910_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="session910_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="session910_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="session910_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>session910</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="session910_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="session910_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="session910_files/libs/revealjs/dist/theme/quarto-77fa2cb3bc1469902a4e0e907f0733e5.css">
  <link href="session910_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="session910_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="session910_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="session910_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section class="slide level2">

<style>
body {
  font-family: 'Trebuchet MS', sans-serif;
}
.reveal h1, .reveal h2, .reveal h3, .reveal h4 {
  color: #2980b9;
}
.reveal {
  font-family: 'Trebuchet MS', sans-serif;
}
</style>
<div style="text-align:center; margin-top: 40px; line-height: 1.4;">
<p><img src="https://pelprek.sgp1.digitaloceanspaces.com/banner/3489/148825024520275.png" alt="PPIU Logo" style="width: 400px; margin-bottom: 20px;"></p>
<h1 style="font-size: 3em; font-weight: 700; color: #2980b9; margin-bottom: 10px;">
Statistics for Data Analysis
</h1>
<h2 style="font-size: 1.6em; font-weight: 500; color: #555;">
Descriptive Statistics: Central Tendency &amp; Dispersion
</h2>
<div style="border-bottom: 4px solid #e74c3c; width: 45%; margin: 18px auto;">

</div>
<h3 style="margin-top: 25px; font-weight: 700; color: #050E3C">
By: MIN Sothearith
</h3>
<h4 style="font-weight: 700; color: #666;">
Phnom Penh International University
</h4>
</div>
</section>
<section id="welcome" class="slide level2">
<h2>Welcome! 📊</h2>
<div style="text-align:center; margin-top: 40px;">
<h3 style="color: #2980b9;">
Understanding Data Through Numbers
</h3>
<p style="font-size: 1.4em; margin-top: 50px;">
Today we learn how to <strong>summarize</strong>, <strong>describe</strong>, and <strong>understand</strong> data using statistics! 🚀
</p>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Why It Matters</strong></p>
</div>
<div class="callout-content">
<p>Raw data is just a pile of numbers. Descriptive statistics turns that pile into <strong>insight</strong> — answering “what is typical?” and “how spread out is the data?”</p>
</div>
</div>
</div>
</section>
<section id="todays-plan" class="slide level2 scrollable">
<h2>Today’s Plan</h2>
<p><strong>Descriptive Statistics — 3 Hours:</strong></p>
<ol type="1">
<li><strong>Introduction</strong> — What is descriptive statistics and why do we use it?</li>
<li><strong>Part 1: Measures of Central Tendency</strong> — Mean, Median, Mode</li>
<li><strong>Part 2: Measures of Dispersion</strong> — Range, Variance, Standard Deviation, IQR</li>
<li><strong>Part 3: Choosing the Right Measure</strong> — When to use what</li>
<li><strong>Part 4: Real-World Use Cases &amp; Projects</strong></li>
<li><strong>Part 5: Computing with Python</strong></li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>⏱️ Time:</strong> ~3 hours | <strong>📝 Goal:</strong> Describe any dataset with confidence using the right statistics!</p>
</div>
</div>
</div>
</section>
<section id="learning-objectives" class="slide level2">
<h2>Learning Objectives</h2>
<p><strong>By the end of this class, you will:</strong></p>
<ul>
<li>Understand what descriptive statistics summarizes about data</li>
<li>Calculate and interpret mean, median, and mode</li>
<li>Calculate and interpret range, variance, standard deviation, and IQR</li>
<li>Know which measure is best for different types of data</li>
<li>Detect outliers and understand their effect</li>
<li>Apply descriptive statistics to real-world datasets using Python</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 Hands-On Learning</strong></p>
</div>
<div class="callout-content">
<p>Every concept comes with manual calculation, real-world examples, and Python code!</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section>
<section>
<section id="introduction-what-is-descriptive-statistics" class="title-slide slide level1 center">
<h1>Introduction: What is Descriptive Statistics?</h1>

</section>
<section id="data-without-statistics" class="slide level2">
<h2>Data Without Statistics</h2>
<p>Imagine you receive this dataset — exam scores from 20 students:</p>
<pre><code>72, 85, 91, 63, 78, 55, 88, 94, 71, 67,
82, 79, 95, 60, 74, 88, 53, 77, 83, 69</code></pre>
<p><strong>Questions a teacher might ask:</strong></p>
<ul>
<li>What is the <em>typical</em> score in this class?</li>
<li>Are students’ scores close together or very spread out?</li>
<li>Is the class performing well overall?</li>
<li>Are there any unusually high or low scores?</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 The Problem</strong></p>
</div>
<div class="callout-content">
<p>20 numbers are manageable. But what about 2,000? Or 200,000? We need tools to <strong>summarize</strong> data into meaningful numbers.</p>
</div>
</div>
</div>
</section>
<section id="two-main-questions-in-descriptive-statistics" class="slide level2">
<h2>Two Main Questions in Descriptive Statistics</h2>
<div style="text-align:center; margin-top: 20px;">
<table class="caption-top">
<colgroup>
<col style="width: 31%">
<col style="width: 40%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Answered By</th>
<th>Examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What is the typical value?</strong></td>
<td>Measures of <strong>Central Tendency</strong></td>
<td>Mean, Median, Mode</td>
</tr>
<tr class="even">
<td><strong>How spread out is the data?</strong></td>
<td>Measures of <strong>Dispersion</strong></td>
<td>Range, Variance, Std Dev, IQR</td>
</tr>
</tbody>
</table>
</div>
<pre><code>Data: 55, 63, 67, 69, 71, 72, 74, 77, 78, 79,
      82, 83, 85, 88, 88, 91, 94, 95, 53, 60

Central Tendency → "The typical score is around 76"
Dispersion       → "Scores range from 53 to 95 — quite spread out"</code></pre>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Together they tell the full story</strong></p>
</div>
<div class="callout-content">
<p>A mean of 76 means very different things if the std deviation is 3 (tight cluster) vs 20 (very spread out).</p>
</div>
</div>
</div>
</section>
<section id="real-world-applications" class="slide level2">
<h2>Real-World Applications</h2>
<p><strong>Where descriptive statistics is used every day:</strong></p>
<ul>
<li>🏥 <strong>Healthcare</strong> — Average patient recovery time, spread of blood pressure readings</li>
<li>🏫 <strong>Education</strong> — Class average, score distribution, identifying struggling students</li>
<li>💰 <strong>Finance</strong> — Average stock return, volatility (dispersion) of investments</li>
<li>🌦️ <strong>Weather</strong> — Mean temperature, typical rainfall variation</li>
<li>🏭 <strong>Manufacturing</strong> — Average product weight, quality control tolerance</li>
<li>🛒 <strong>Business</strong> — Average customer spending, variation in daily sales</li>
<li>⚽ <strong>Sports</strong> — Average goals per game, consistency of a player’s performance</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 Before any advanced analysis</strong></p>
</div>
<div class="callout-content">
<p>Descriptive statistics is always the <strong>first step</strong> — you must understand your data before modeling it!</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-1-measures-of-central-tendency" class="title-slide slide level1 center">
<h1>Part 1: Measures of Central Tendency</h1>

</section>
<section id="what-is-central-tendency" class="slide level2">
<h2>What is Central Tendency?</h2>
<h3 style="color: #2980b9; font-size: 1.4em;" id="a-measure-of-central-tendency-finds-the-center-or-typical-value-of-a-dataset">A measure of <strong>central tendency</strong> finds the <strong>center</strong> or <strong>typical value</strong> of a dataset</h3>
<p><strong>Three measures:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 31%">
<col style="width: 37%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Definition</th>
<th>Best For</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Mean</strong></td>
<td>Sum of all values ÷ count</td>
<td>Symmetric data, no outliers</td>
</tr>
<tr class="even">
<td><strong>Median</strong></td>
<td>Middle value when sorted</td>
<td>Skewed data, outliers present</td>
</tr>
<tr class="odd">
<td><strong>Mode</strong></td>
<td>Most frequently occurring value</td>
<td>Categorical data, finding peaks</td>
</tr>
</tbody>
</table>
<p><strong>Intuition:</strong></p>
<ul>
<li><strong>Mean</strong> — the “fair share” if you redistributed everything equally</li>
<li><strong>Median</strong> — the “middle person” in a line sorted by height</li>
<li><strong>Mode</strong> — the “most popular” item in a store</li>
</ul>
</section>
<section id="the-mean-average" class="slide level2">
<h2>1.1 — The Mean (Average)</h2>
<p><strong>Formula:</strong></p>
<p><span class="math display">\[\bar{x} = \frac{\sum_{i=1}^{n} x_i}{n} = \frac{x_1 + x_2 + \cdots + x_n}{n}\]</span></p>
<p><strong>Step-by-step example — Weekly sales ($):</strong></p>
<pre><code>Data: 200, 350, 280, 410, 300</code></pre>
<p><strong>Calculate:</strong></p>
<p><span class="math display">\[\bar{x} = \frac{200 + 350 + 280 + 410 + 300}{5} = \frac{1540}{5} = 308\]</span></p>
<p>The <strong>mean weekly sales is $308</strong>.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Intuition</strong></p>
</div>
<div class="callout-content">
<p>If you spread the total sales ($1,540) equally across all 5 days, each day would have $308.</p>
</div>
</div>
</div>
</section>
<section id="mean-more-examples" class="slide level2">
<h2>Mean — More Examples</h2>
<p><strong>Example 1: Student test scores</strong></p>
<pre><code>Scores: 70, 85, 90, 60, 75
Mean = (70 + 85 + 90 + 60 + 75) / 5 = 380 / 5 = 76</code></pre>
<p><strong>Example 2: Daily temperatures (°C)</strong></p>
<pre><code>Mon: 28, Tue: 31, Wed: 29, Thu: 35, Fri: 27, Sat: 30, Sun: 32
Mean = (28+31+29+35+27+30+32) / 7 = 212 / 7 ≈ 30.3°C</code></pre>
<p><strong>Example 3: Hospital patient ages</strong></p>
<pre><code>Ages: 25, 34, 45, 67, 23, 54, 38, 29
Mean = (25+34+45+67+23+54+38+29) / 8 = 315 / 8 ≈ 39.4 years</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🔢 Symbol note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\bar{x}\)</span> (x-bar) = sample mean | <span class="math inline">\(\mu\)</span> (mu) = population mean</p>
</div>
</div>
</div>
</section>
<section id="mean-the-outlier-problem" class="slide level2">
<h2>Mean — The Outlier Problem</h2>
<p>The mean is <strong>sensitive to extreme values (outliers)</strong>:</p>
<p><strong>Example: Monthly salaries at a small company ($)</strong></p>
<pre><code>Employee A: 1,200
Employee B: 1,400
Employee C: 1,300
Employee D: 1,500
CEO:       50,000</code></pre>
<p><span class="math display">\[\bar{x} = \frac{1200 + 1400 + 1300 + 1500 + 50000}{5} = \frac{55400}{5} = 11080\]</span></p>
<p><strong>Is $11,080 a “typical” salary here? NO!</strong> Four out of five people earn around $1,350.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>⚠️ Outlier Effect</strong></p>
</div>
<div class="callout-content">
<p>One extreme value (the CEO’s salary) pulled the mean far above the typical salary. This is when we use the <strong>Median</strong> instead!</p>
</div>
</div>
</div>
</section>
<section id="the-median" class="slide level2 scrollable">
<h2>1.2 — The Median</h2>
<p><strong>The Median is the middle value when data is sorted.</strong></p>
<p><strong>Steps to find the Median:</strong></p>
<ol type="1">
<li><strong>Sort</strong> the data from smallest to largest</li>
<li><strong>If n is odd</strong> → median = middle value</li>
<li><strong>If n is even</strong> → median = average of two middle values</li>
</ol>
<p><strong>Example 1 (odd count — 5 values):</strong></p>
<pre><code>Unsorted: 85, 70, 90, 60, 75
Sorted:   60, 70, 75, 85, 90
                   ↑
              Median = 75</code></pre>
<p><strong>Example 2 (even count — 6 values):</strong></p>
<pre><code>Unsorted: 85, 70, 90, 60, 75, 80
Sorted:   60, 70, 75, 80, 85, 90
                   ↑  ↑
              Median = (75 + 80) / 2 = 77.5</code></pre>
</section>
<section id="median-resistant-to-outliers" class="slide level2">
<h2>Median — Resistant to Outliers</h2>
<p><strong>Same salary example as before:</strong></p>
<pre><code>Sorted: 1,200 | 1,300 | 1,400 | 1,500 | 50,000
                          ↑
                    Median = 1,400</code></pre>
<p><strong>Mean = $11,080</strong> — misleading! <strong>Median = $1,400</strong> — much more representative of a typical employee!</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 Key Insight</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Real estate: “median home price” (not mean) — because a few mansions skew the mean</li>
<li>Income reports: “median household income” — because billionaires skew the mean</li>
<li>The <strong>median</strong> always tells you “half the values are below this, half are above”</li>
</ul>
</div>
</div>
</div>
</section>
<section id="median-more-examples" class="slide level2">
<h2>Median — More Examples</h2>
<p><strong>Example: House prices in a neighborhood ($1000s)</strong></p>
<pre><code>Sorted: 120, 135, 150, 165, 180, 195, 850
                         ↑
                    Median = 165 (thousand)
Mean = (120+135+150+165+180+195+850)/7 = 256 (thousand)</code></pre>
<p>The $850k mansion pulls the mean to $256k, but median says $165k is typical.</p>
<p><strong>Example: Response times for a website (ms)</strong></p>
<pre><code>Sorted: 120, 125, 130, 135, 140, 145, 980
Median = 135 ms   ← typical user experience
Mean   = 253 ms   ← distorted by 1 slow request</code></pre>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Use Median when</strong></p>
</div>
<div class="callout-content">
<p>Your data has outliers, or is skewed (not symmetric).</p>
</div>
</div>
</div>
</section>
<section id="the-mode" class="slide level2">
<h2>1.3 — The Mode</h2>
<p><strong>The Mode is the value that appears most frequently.</strong></p>
<p><strong>Simple example:</strong></p>
<pre><code>Data: 3, 7, 3, 9, 3, 5, 7, 2
Mode = 3  (appears 3 times — more than any other)</code></pre>
<p><strong>Multiple modes:</strong></p>
<pre><code>Data: 2, 4, 4, 6, 8, 8, 10
Mode = 4 and 8  (both appear twice → Bimodal)</code></pre>
<p><strong>No mode:</strong></p>
<pre><code>Data: 1, 2, 3, 4, 5
Mode = None  (all values appear once)</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🔢 Types of mode distribution</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Unimodal</strong> — one mode (one peak)</li>
<li><strong>Bimodal</strong> — two modes (two peaks)</li>
<li><strong>Multimodal</strong> — three or more modes</li>
<li><strong>No mode</strong> — all values unique</li>
</ul>
</div>
</div>
</div>
</section>
<section id="mode-real-world-use-cases" class="slide level2">
<h2>Mode — Real-World Use Cases</h2>
<p><strong>Example 1: Shoe sizes sold in a store</strong></p>
<pre><code>Sizes: 38, 40, 39, 41, 40, 40, 38, 42, 40, 39
Mode = 40  ← The store should stock the most size 40!</code></pre>
<p><strong>Example 2: Favorite subject (survey of 15 students)</strong></p>
<pre><code>Math, Science, Math, Khmer, English, Math, Science,
Math, English, Khmer, Math, Science, Math, English, Math
Mode = Math  ← Most popular subject</code></pre>
<p><strong>Example 3: Number of siblings</strong></p>
<pre><code>Data: 0, 1, 2, 1, 3, 1, 0, 2, 1, 4, 1
Mode = 1  ← Most families have 1 sibling</code></pre>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 Mode is the ONLY measure for categorical data</strong></p>
</div>
<div class="callout-content">
<p>You cannot compute a mean or median of colors, names, or categories — but you CAN find a mode!</p>
</div>
</div>
</div>
</section>
<section id="comparing-mean-median-mode" class="slide level2">
<h2>Comparing Mean, Median, Mode</h2>
<p><strong>Dataset: Monthly income of 9 households ($)</strong></p>
<pre><code>800, 900, 950, 1000, 1050, 1100, 1200, 1300, 8000</code></pre>
<table class="caption-top">
<thead>
<tr class="header">
<th>Measure</th>
<th>Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Mean</strong></td>
<td>$1,811</td>
<td>Pulled up by outlier</td>
</tr>
<tr class="even">
<td><strong>Median</strong></td>
<td>$1,050</td>
<td>Middle household income</td>
</tr>
<tr class="odd">
<td><strong>Mode</strong></td>
<td>None</td>
<td>All values unique</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Which to report?</strong></p>
</div>
<div class="callout-content">
<p>In this case, <strong>median</strong> best represents a “typical” household. The mean of $1,811 would mislead people into thinking incomes are higher than they really are.</p>
</div>
</div>
</div>
</section>
<section id="symmetric-vs-skewed-data" class="slide level2">
<h2>Symmetric vs Skewed Data</h2>
<p>The <strong>relationship between mean and median</strong> reveals the shape of data:</p>
<pre><code>Symmetric (normal):   Mean ≈ Median ≈ Mode
                      [Bell curve — mean is reliable]

Right-skewed:         Mode &lt; Median &lt; Mean
                      [Long tail to the right — median is safer]
                      Example: income, house prices

Left-skewed:          Mean &lt; Median &lt; Mode
                      [Long tail to the left]
                      Example: age at retirement</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🔍 Quick check</strong></p>
</div>
<div class="callout-content">
<p>If mean &gt; median → data is likely right-skewed (pulled by high outliers) If mean &lt; median → data is likely left-skewed (pulled by low outliers)</p>
</div>
</div>
</div>
</section>
<section id="practice-1a-calculate-by-hand" class="slide level2 scrollable">
<h2>Practice 1A — Calculate by Hand</h2>
<p><strong>Dataset: Exam scores of 10 students</strong></p>
<pre><code>88, 73, 95, 61, 88, 77, 84, 91, 61, 72</code></pre>
<p>Calculate:</p>
<ol type="1">
<li><strong>Mean</strong> = ?</li>
<li><strong>Median</strong> = ? <em>(sort first!)</em></li>
<li><strong>Mode</strong> = ?</li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>✏️ Work it out</strong></p>
</div>
<div class="callout-content">
<p>Sorted: 61, 61, 72, 73, 77, 84, 88, 88, 91, 95</p>
<p>Mean = (61+61+72+73+77+84+88+88+91+95) / 10 = 790 / 10 = <strong>79.0</strong></p>
<p>Median = (77 + 84) / 2 = <strong>80.5</strong> ← average of 5th and 6th values</p>
<p>Mode = <strong>61 and 88</strong> ← both appear twice (Bimodal)</p>
</div>
</div>
</div>
</section>
<section id="practice-1b-salary-analysis" class="slide level2 scrollable">
<h2>Practice 1B — Salary Analysis</h2>
<p><strong>A company has these employee salaries ($/month):</strong></p>
<pre><code>2,500 | 2,800 | 3,100 | 2,800 | 2,600 | 2,800 | 45,000</code></pre>
<ol type="1">
<li>Compute the <strong>mean</strong>, <strong>median</strong>, and <strong>mode</strong></li>
<li>Which measure best represents a “typical” salary? Why?</li>
<li>The CEO earns $45,000 — how does this affect each measure?</li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>✏️ Solution</strong></p>
</div>
<div class="callout-content">
<p>Mean = (2500+2800+3100+2800+2600+2800+45000)/7 = 61600/7 ≈ <strong>$8,800</strong></p>
<p>Sorted: 2500, 2600, 2800, 2800, 2800, 3100, 45000</p>
<p>Median = <strong>$2,800</strong> (4th value)</p>
<p>Mode = <strong>$2,800</strong> (appears 3 times)</p>
<p>→ <strong>Median and Mode are better here.</strong> The CEO’s salary ($45k) inflates the mean dramatically.</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-2-measures-of-dispersion" class="title-slide slide level1 center">
<h1>Part 2: Measures of Dispersion</h1>

</section>
<section id="what-is-dispersion" class="slide level2">
<h2>What is Dispersion?</h2>
<h3 style="color: #2980b9; font-size: 1.4em;" id="dispersion-measures-how-spread-out-or-scattered-the-data-values-are"><strong>Dispersion</strong> measures how <strong>spread out</strong> or <strong>scattered</strong> the data values are</h3>
<p><strong>Why does it matter?</strong></p>
<pre><code>Class A scores: 75, 76, 74, 75, 75, 76    → Mean = 75.2
Class B scores: 50, 60, 95, 40, 100, 81   → Mean = 71.0</code></pre>
<p>Just knowing the mean doesn’t tell the whole story! Class A is consistent; Class B is wildly varied.</p>
<p><strong>Four key measures of dispersion:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Measure</th>
<th>What it tells you</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Range</strong></td>
<td>The full spread (max − min)</td>
</tr>
<tr class="even">
<td><strong>Variance</strong></td>
<td>Average squared distance from the mean</td>
</tr>
<tr class="odd">
<td><strong>Standard Deviation</strong></td>
<td>Typical distance from the mean</td>
</tr>
<tr class="even">
<td><strong>IQR</strong></td>
<td>Spread of the middle 50%</td>
</tr>
</tbody>
</table>
</section>
<section id="range" class="slide level2">
<h2>2.1 — Range</h2>
<p><strong>Range = Maximum value − Minimum value</strong></p>
<p><span class="math display">\[\text{Range} = x_{\max} - x_{\min}\]</span></p>
<p><strong>Example 1: Daily temperatures (°C)</strong></p>
<pre><code>Data: 22, 27, 31, 19, 35, 28, 24
Min = 19,  Max = 35
Range = 35 − 19 = 16°C</code></pre>
<p><strong>Example 2: Marathon finishing times (minutes)</strong></p>
<pre><code>Data: 210, 185, 240, 195, 228, 175, 260
Min = 175,  Max = 260
Range = 260 − 175 = 85 minutes</code></pre>
<p><strong>Example 3: Student test scores</strong></p>
<pre><code>Data: 45, 62, 78, 88, 91, 55, 70
Min = 45,  Max = 91
Range = 91 − 45 = 46 points</code></pre>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>⚠️ Limitation of Range</strong></p>
</div>
<div class="callout-content">
<p>Range only uses 2 values (min and max). One extreme outlier completely changes it!</p>
</div>
</div>
</div>
</section>
<section id="range-limitation-example" class="slide level2">
<h2>Range — Limitation Example</h2>
<pre><code>Dataset A: 10, 20, 30, 40, 50
Range = 50 − 10 = 40

Dataset B: 10, 29, 30, 31, 50
Range = 50 − 10 = 40  ← Same range!</code></pre>
<p>But Dataset A is evenly spread; Dataset B is mostly clustered around 30.</p>
<p><strong>Range cannot capture this difference.</strong> We need better measures!</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Range is useful when</strong></p>
</div>
<div class="callout-content">
<ul>
<li>You just want a quick, simple overview</li>
<li>You are checking if any value is out of an expected range (quality control)</li>
<li>Data has no obvious outliers</li>
</ul>
</div>
</div>
</div>
</section>
<section id="variance" class="slide level2 scrollable">
<h2>2.2 — Variance</h2>
<p><strong>Variance measures the average squared distance of each value from the mean.</strong></p>
<p><span class="math display">\[s^2 = \frac{\sum_{i=1}^{n}(x_i - \bar{x})^2}{n-1}\]</span></p>
<p><em>(We use n−1 for sample variance — Bessel’s correction)</em></p>
<p><strong>Steps:</strong></p>
<ol type="1">
<li>Calculate the <strong>mean</strong> (<span class="math inline">\(\bar{x}\)</span>)</li>
<li>Subtract the mean from each value → <strong>deviations</strong> <span class="math inline">\((x_i - \bar{x})\)</span></li>
<li><strong>Square</strong> each deviation → <span class="math inline">\((x_i - \bar{x})^2\)</span></li>
<li><strong>Sum</strong> all squared deviations</li>
<li><strong>Divide</strong> by <span class="math inline">\(n - 1\)</span></li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Why square the deviations?</strong></p>
</div>
<div class="callout-content">
<p>Without squaring, deviations above and below the mean cancel out to zero! Squaring makes all values positive, so large deviations have a large effect.</p>
</div>
</div>
</div>
</section>
<section id="variance-step-by-step-calculation" class="slide level2">
<h2>Variance — Step-by-Step Calculation</h2>
<p><strong>Dataset: Hours of study per day for 5 students</strong></p>
<pre><code>Data: 2, 4, 4, 6, 4    → Mean = (2+4+4+6+4)/5 = 20/5 = 4</code></pre>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\(x_i - \bar{x}\)</span></th>
<th><span class="math inline">\((x_i - \bar{x})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>2 − 4 = −2</td>
<td>(−2)² = <strong>4</strong></td>
</tr>
<tr class="even">
<td>4</td>
<td>4 − 4 = 0</td>
<td>(0)² = <strong>0</strong></td>
</tr>
<tr class="odd">
<td>4</td>
<td>4 − 4 = 0</td>
<td>(0)² = <strong>0</strong></td>
</tr>
<tr class="even">
<td>6</td>
<td>6 − 4 = +2</td>
<td>(+2)² = <strong>4</strong></td>
</tr>
<tr class="odd">
<td>4</td>
<td>4 − 4 = 0</td>
<td>(0)² = <strong>0</strong></td>
</tr>
<tr class="even">
<td></td>
<td><strong>Sum</strong> = 0</td>
<td><strong>Sum = 8</strong></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[s^2 = \frac{8}{5 - 1} = \frac{8}{4} = 2 \text{ hours}^2\]</span></p>
</section>
<section id="variance-why-units-are-squared" class="slide level2">
<h2>Variance — Why Units Are Squared</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>⚠️ Variance is in squared units</strong></p>
</div>
<div class="callout-content">
<p>If data is in <strong>hours</strong>, variance is in <strong>hours²</strong><br>
If data is in <strong>dollars</strong>, variance is in <strong>dollars²</strong><br>
If data is in <strong>°C</strong>, variance is in <strong>°C²</strong></p>
<p>This makes it <strong>hard to interpret directly</strong> — we can’t say “the typical deviation is 2 hours²”!</p>
<p><strong>Solution → Standard Deviation</strong> (take the square root)</p>
</div>
</div>
</div>
<p><strong>Variance is still useful for:</strong></p>
<ul>
<li>Comparing relative spread between datasets (same units)</li>
<li>Mathematical calculations in advanced statistics</li>
<li>Portfolio risk in finance (portfolio variance)</li>
</ul>
</section>
<section id="standard-deviation" class="slide level2">
<h2>2.3 — Standard Deviation</h2>
<p><strong>Standard Deviation = Square root of the Variance</strong></p>
<p><span class="math display">\[s = \sqrt{s^2} = \sqrt{\frac{\sum_{i=1}^{n}(x_i - \bar{x})^2}{n-1}}\]</span></p>
<p><strong>Continuing our example:</strong></p>
<p><span class="math display">\[s = \sqrt{2} \approx 1.41 \text{ hours}\]</span></p>
<p><strong>Interpretation:</strong> On average, students deviate from the mean study time by about <strong>1.41 hours</strong>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 Standard Deviation is the most widely used measure of spread</strong></p>
</div>
<div class="callout-content">
<p>It is in the <strong>same units as the data</strong>, making it directly interpretable!</p>
</div>
</div>
</div>
</section>
<section id="standard-deviation-full-example" class="slide level2">
<h2>Standard Deviation — Full Example</h2>
<p><strong>Factory Machine A produces bolts with these diameters (mm):</strong></p>
<pre><code>Data: 10.1, 10.2, 9.9, 10.0, 10.3, 9.8, 10.2
Mean = 70.5 / 7 ≈ 10.07 mm</code></pre>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\(x_i - \bar{x}\)</span></th>
<th><span class="math inline">\((x_i - \bar{x})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10.1</td>
<td>+0.03</td>
<td>0.0009</td>
</tr>
<tr class="even">
<td>10.2</td>
<td>+0.13</td>
<td>0.0169</td>
</tr>
<tr class="odd">
<td>9.9</td>
<td>−0.17</td>
<td>0.0289</td>
</tr>
<tr class="even">
<td>10.0</td>
<td>−0.07</td>
<td>0.0049</td>
</tr>
<tr class="odd">
<td>10.3</td>
<td>+0.23</td>
<td>0.0529</td>
</tr>
<tr class="even">
<td>9.8</td>
<td>−0.27</td>
<td>0.0729</td>
</tr>
<tr class="odd">
<td>10.2</td>
<td>+0.13</td>
<td>0.0169</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[s^2 = \frac{0.1943}{6} \approx 0.0324 \quad \Rightarrow \quad s \approx 0.18 \text{ mm}\]</span></p>
<p><strong>The machine’s output varies by about ±0.18 mm</strong> — acceptable or not? Depends on tolerance!</p>
</section>
<section id="standard-deviation-comparing-datasets" class="slide level2">
<h2>Standard Deviation — Comparing Datasets</h2>
<p><strong>This is where standard deviation really shines:</strong></p>
<pre><code>Archer A hits: 85, 86, 84, 85, 85, 84, 86
Mean = 85.0,  Std Dev ≈ 0.82  ← Very consistent! 🎯

Archer B hits: 70, 95, 80, 100, 65, 90, 85
Mean = 83.6,  Std Dev ≈ 13.0  ← Very inconsistent! 😬</code></pre>
<p><strong>Similar means, very different standard deviations!</strong></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Real-world comparisons</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Investment risk:</strong> Low std dev = stable returns, High std dev = volatile (risky)</li>
<li><strong>Manufacturing:</strong> Low std dev = consistent quality, High std dev = defects</li>
<li><strong>Exam results:</strong> Low std dev = similar performance, High std dev = mixed class</li>
</ul>
</div>
</div>
</div>
</section>
<section id="standard-deviation-the-68-95-99.7-rule" class="slide level2">
<h2>Standard Deviation — The 68-95-99.7 Rule</h2>
<p>For <strong>normally distributed data</strong>, standard deviation has a powerful interpretation:</p>
<p><span class="math display">\[\mu \pm 1s \rightarrow \approx 68\% \text{ of data}\]</span> <span class="math display">\[\mu \pm 2s \rightarrow \approx 95\% \text{ of data}\]</span> <span class="math display">\[\mu \pm 3s \rightarrow \approx 99.7\% \text{ of data}\]</span></p>
<p><strong>Example: Exam scores with Mean = 75, Std Dev = 10</strong></p>
<pre><code>68% of students scored between 65 and 85   (75 ± 10)
95% of students scored between 55 and 95   (75 ± 20)
99.7% of students scored between 45 and 105 (75 ± 30)</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🔍 Practical use</strong></p>
</div>
<div class="callout-content">
<p>A score more than 2 standard deviations from the mean is unusual (only 5% of the data). This is the basis of detecting <strong>outliers</strong>!</p>
</div>
</div>
</div>
</section>
<section id="interquartile-range-iqr" class="slide level2 scrollable">
<h2>2.4 — Interquartile Range (IQR)</h2>
<p><strong>IQR measures the spread of the middle 50% of data.</strong></p>
<p><strong>Steps:</strong></p>
<ol type="1">
<li>Sort the data</li>
<li>Find <strong>Q1</strong> (25th percentile — median of the lower half)</li>
<li>Find <strong>Q3</strong> (75th percentile — median of the upper half)</li>
<li><strong>IQR = Q3 − Q1</strong></li>
</ol>
<p><strong>Example: Delivery times (minutes)</strong></p>
<pre><code>Sorted: 15, 18, 20, 22, 25, 28, 30, 35, 40, 45
              ↑                          ↑
             Q1                         Q3

Lower half:  15, 18, 20, 22, 25  →  Q1 = 20
Upper half:  28, 30, 35, 40, 45  →  Q3 = 35

IQR = Q3 − Q1 = 35 − 20 = 15 minutes</code></pre>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 IQR ignores outliers completely</strong></p>
</div>
<div class="callout-content">
<p>Only looks at the middle 50%, so extreme values have NO effect!</p>
</div>
</div>
</div>
</section>
<section id="iqr-outlier-detection" class="slide level2">
<h2>IQR — Outlier Detection</h2>
<p>IQR is used to formally define outliers:</p>
<p><span class="math display">\[\text{Lower fence} = Q1 - 1.5 \times IQR\]</span> <span class="math display">\[\text{Upper fence} = Q3 + 1.5 \times IQR\]</span></p>
<p><strong>Values outside these fences are outliers!</strong></p>
<p><strong>Example: Continuing from before (IQR = 15, Q1 = 20, Q3 = 35)</strong></p>
<pre><code>Lower fence = 20 − 1.5 × 15 = 20 − 22.5 = −2.5
Upper fence = 35 + 1.5 × 15 = 35 + 22.5 = 57.5

Any delivery time below −2.5 or above 57.5 is an outlier.</code></pre>
<p>Now add a bad day: <code>15, 18, 20, 22, 25, 28, 30, 35, 40, 45, **120**</code></p>
<pre><code>120 &gt; 57.5 → 120 is an OUTLIER! 🚨</code></pre>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Box plots</strong></p>
</div>
<div class="callout-content">
<p>IQR is the foundation of the <strong>box plot</strong> (box-and-whisker plot) — a key visualization in data analysis!</p>
</div>
</div>
</div>
</section>
<section id="comparing-all-dispersion-measures" class="slide level2">
<h2>Comparing All Dispersion Measures</h2>
<p><strong>Dataset: Monthly expenses ($) of 8 students</strong></p>
<pre><code>Data: 150, 200, 180, 500, 160, 190, 170, 180</code></pre>
<table class="caption-top">
<colgroup>
<col style="width: 29%">
<col style="width: 22%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Range</td>
<td>500 − 150 = <strong>$350</strong></td>
<td>Full spread — affected by $500 outlier</td>
</tr>
<tr class="even">
<td>Variance</td>
<td><strong>$10,250</strong></td>
<td>Squared dollars — hard to interpret</td>
</tr>
<tr class="odd">
<td>Std Dev</td>
<td><strong>≈ $101</strong></td>
<td>Average deviation from mean</td>
</tr>
<tr class="even">
<td>IQR</td>
<td><strong>$30</strong></td>
<td>Middle 50% has only $30 variation!</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🔍 Insight</strong></p>
</div>
<div class="callout-content">
<p>The IQR of $30 reveals that most students spend similarly. The high range and std dev are caused by just one outlier ($500). Remove that student and the data is very tight.</p>
</div>
</div>
</div>
</section>
<section id="practice-2a-calculate-dispersion-by-hand" class="slide level2 scrollable">
<h2>Practice 2A — Calculate Dispersion by Hand</h2>
<p><strong>Dataset: Heights of 7 basketball players (cm)</strong></p>
<pre><code>185, 192, 178, 201, 188, 195, 183</code></pre>
<p>Calculate:</p>
<ol type="1">
<li><strong>Range</strong> = ?</li>
<li><strong>Mean</strong> = ?</li>
<li><strong>Variance</strong> = ? <em>(show the deviation table)</em></li>
<li><strong>Standard Deviation</strong> = ?</li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>✏️ Solution</strong></p>
</div>
<div class="callout-content">
<p>Mean = (185+192+178+201+188+195+183)/7 = 1322/7 ≈ <strong>188.9 cm</strong></p>
<p>Range = 201 − 178 = <strong>23 cm</strong></p>
<p>Deviations²: (−3.9)²=15.2, (3.1)²=9.6, (−10.9)²=118.8, (12.1)²=146.4, (−0.9)²=0.8, (6.1)²=37.2, (−5.9)²=34.8</p>
<p>Variance = (15.2+9.6+118.8+146.4+0.8+37.2+34.8)/6 = 362.8/6 ≈ <strong>60.5 cm²</strong></p>
<p>Std Dev = √60.5 ≈ <strong>7.78 cm</strong></p>
</div>
</div>
</div>
</section>
<section id="practice-2b-iqr-and-outlier-detection" class="slide level2 scrollable">
<h2>Practice 2B — IQR and Outlier Detection</h2>
<p><strong>Dataset: Daily number of customer complaints for 11 days</strong></p>
<pre><code>3, 5, 4, 7, 6, 4, 5, 3, 4, 50, 5</code></pre>
<ol type="1">
<li>Sort the data and find Q1, Q3, and IQR</li>
<li>Calculate the outlier fences</li>
<li>Identify any outliers</li>
<li>What does the outlier suggest about that day?</li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>✏️ Solution</strong></p>
</div>
<div class="callout-content">
<p>Sorted: 3, 3, 4, 4, 4, 5, 5, 5, 6, 7, 50</p>
<p>Q1 = 4 (median of lower half: 3,3,4,4,4) Q3 = 6 (median of upper half: 5,5,6,7,50)</p>
<p>IQR = 6 − 4 = <strong>2</strong></p>
<p>Lower fence = 4 − 1.5×2 = <strong>1</strong> Upper fence = 6 + 1.5×2 = <strong>9</strong></p>
<p>50 &gt; 9 → <strong>50 is an outlier!</strong> 🚨 Something unusual happened that day — investigate!</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-3-choosing-the-right-measure" class="title-slide slide level1 center">
<h1>Part 3: Choosing the Right Measure</h1>

</section>
<section id="when-to-use-each-measure" class="slide level2">
<h2>When to Use Each Measure</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Situation</th>
<th>Central Tendency</th>
<th>Dispersion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Symmetric data, no outliers</td>
<td><strong>Mean</strong></td>
<td><strong>Std Dev / Variance</strong></td>
</tr>
<tr class="even">
<td>Skewed data or outliers</td>
<td><strong>Median</strong></td>
<td><strong>IQR</strong></td>
</tr>
<tr class="odd">
<td>Categorical data</td>
<td><strong>Mode</strong></td>
<td>N/A</td>
</tr>
<tr class="even">
<td>Finding most common value</td>
<td><strong>Mode</strong></td>
<td>—</td>
</tr>
<tr class="odd">
<td>Comparing spread across groups</td>
<td><strong>Mean</strong></td>
<td><strong>Std Dev</strong></td>
</tr>
<tr class="even">
<td>Outlier detection</td>
<td><strong>Median</strong></td>
<td><strong>IQR</strong></td>
</tr>
<tr class="odd">
<td>Financial risk analysis</td>
<td><strong>Mean</strong></td>
<td><strong>Variance / Std Dev</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 The Golden Rule</strong></p>
</div>
<div class="callout-content">
<p>When data has <strong>outliers</strong> → prefer <strong>Median + IQR</strong> When data is <strong>clean and symmetric</strong> → prefer <strong>Mean + Std Dev</strong></p>
</div>
</div>
</div>
</section>
<section id="decision-guide-real-scenarios" class="slide level2">
<h2>Decision Guide — Real Scenarios</h2>
<p><strong>Scenario 1:</strong> A city reports average income to attract investors → Outliers (rich residents) exist → Use <strong>Median</strong></p>
<p><strong>Scenario 2:</strong> A factory monitors bolt diameter for quality control → Data should be symmetric, precise → Use <strong>Mean + Std Dev</strong></p>
<p><strong>Scenario 3:</strong> A hospital tracks patient wait times → Long waits are outliers → Use <strong>Median + IQR</strong></p>
<p><strong>Scenario 4:</strong> A poll asks voters’ favorite candidate → Categorical data → Use <strong>Mode</strong></p>
<p><strong>Scenario 5:</strong> A teacher compares two classes’ exam consistency → Compare variability → Use <strong>Std Dev</strong></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Always visualize first!</strong></p>
</div>
<div class="callout-content">
<p>A quick histogram or box plot helps you see the shape of data and choose the right measure.</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-4-real-world-use-cases" class="title-slide slide level1 center">
<h1>Part 4: Real-World Use Cases</h1>

</section>
<section id="use-case-1-analyzing-exam-results" class="slide level2">
<h2>Use Case 1 — Analyzing Exam Results</h2>
<p><strong>Scenario:</strong> A teacher has exam scores from 15 students:</p>
<pre><code>55, 62, 70, 73, 75, 78, 80, 82, 82, 85, 88, 90, 92, 95, 45</code></pre>
<p><strong>Analysis:</strong></p>
<pre><code>Mean   = (sum) / 15 = 1152 / 15 = 76.8
Median = 82  (8th value)
Mode   = 82  (appears twice)
Range  = 95 − 45 = 50
Std Dev ≈ 14.2
Q1 = 72,  Q3 = 89,  IQR = 17
Outlier check: Lower = 72 − 25.5 = 46.5 → 45 is borderline!
               Upper = 89 + 25.5 = 114.5 → No high outliers</code></pre>
<p><strong>Insights:</strong> Mean ≈ Median → roughly symmetric. Score of 45 may need attention. Std dev of 14.2 indicates moderate spread.</p>
</section>
<section id="use-case-2-e-commerce-sales-analysis" class="slide level2">
<h2>Use Case 2 — E-Commerce Sales Analysis</h2>
<p><strong>Scenario:</strong> Daily revenue ($) for an online store over 10 days:</p>
<pre><code>1200, 980, 1450, 1100, 1320, 850, 5600, 1250, 1180, 1070</code></pre>
<pre><code>Mean   = 15000 / 10 = $1,500
Median = (1200 + 1250) / 2 = $1,225   ← better "typical day"
Mode   = None (all unique)
Range  = 5600 − 850 = $4,750
Std Dev ≈ $1,398  (very large — driven by $5,600 outlier)
Q1 = 1035, Q3 = 1387.5, IQR = $352.5
Outlier: Upper fence = 1387.5 + 1.5×352.5 = $1,916
→ $5,600 IS an outlier! (Probably a flash sale or viral post)</code></pre>
<p><strong>Business insight:</strong> A “typical” day brings in ~$1,225. The $5,600 day was exceptional — don’t plan budgets around it!</p>
</section>
<section id="use-case-3-quality-control-in-manufacturing" class="slide level2">
<h2>Use Case 3 — Quality Control in Manufacturing</h2>
<p><strong>Scenario:</strong> A machine fills bottles with juice. Target: 500ml. Sample (ml):</p>
<pre><code>499.2, 500.1, 498.8, 500.5, 499.7, 500.2, 501.0, 499.5, 500.3, 498.9</code></pre>
<pre><code>Mean   = 4998.2 / 10 = 499.82 ml   (close to target ✅)
Std Dev ≈ 0.67 ml

Acceptable range: 500 ± 2ml = [498, 502]
All values within range → Machine is operating correctly ✅

If Std Dev were 5 ml → values would spread from ~490 to ~510
→ Many bottles would be out of specification ❌</code></pre>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 Quality Control Rule</strong></p>
</div>
<div class="callout-content">
<p>Small std dev = consistent quality. Large std dev = inconsistent = defects and waste. The <strong>mean tells you if you’re on target; std dev tells you how consistent you are</strong>.</p>
</div>
</div>
</div>
</section>
<section id="use-case-4-finance-investment-risk" class="slide level2">
<h2>Use Case 4 — Finance &amp; Investment Risk</h2>
<p><strong>Scenario:</strong> Monthly returns (%) for two investment funds:</p>
<pre><code>Fund A: 2.1, 1.8, 2.3, 2.0, 1.9, 2.2, 2.0, 1.7, 2.1, 2.4
Fund B: 5.2, −3.1, 8.4, −2.0, 6.7, −1.5, 9.1, −4.2, 7.3, 1.1</code></pre>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Fund A</th>
<th>Fund B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean return</td>
<td><strong>2.05%</strong></td>
<td><strong>2.70%</strong></td>
</tr>
<tr class="even">
<td>Std Dev</td>
<td><strong>0.21%</strong></td>
<td><strong>5.23%</strong></td>
</tr>
<tr class="odd">
<td>Min/Max</td>
<td>1.7% / 2.4%</td>
<td>−4.2% / 9.1%</td>
</tr>
</tbody>
</table>
<p><strong>Analysis:</strong> Fund B has higher average returns, but 25× more volatility than Fund A!</p>
<ul>
<li>Conservative investor (near retirement) → Choose <strong>Fund A</strong></li>
<li>Aggressive investor (young, long-term) → May choose <strong>Fund B</strong></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 In finance, Std Dev = Risk</strong></p>
</div>
<div class="callout-content">
<p>The entire field of portfolio management is built on this insight!</p>
</div>
</div>
</div>
</section>
<section id="use-case-5-healthcare-blood-pressure-study" class="slide level2">
<h2>Use Case 5 — Healthcare: Blood Pressure Study</h2>
<p><strong>Scenario:</strong> Systolic blood pressure (mmHg) of 12 patients:</p>
<pre><code>115, 122, 118, 135, 128, 120, 142, 119, 125, 130, 116, 180</code></pre>
<pre><code>Mean   = 1550 / 12 ≈ 129.2 mmHg
Median = (122 + 125) / 2 = 123.5 mmHg
Std Dev ≈ 18.4 mmHg
Q1 = 118.25,  Q3 = 131.25,  IQR = 13.0

Outlier fence: 131.25 + 1.5×13 = 150.75
→ 180 mmHg is an OUTLIER 🚨 → Hypertensive crisis! Needs immediate attention!</code></pre>
<p><strong>Clinical insight:</strong> Most patients are near-normal (median 123.5), but one patient at 180 mmHg requires urgent intervention. The outlier detection potentially saves a life!</p>
</section>
<section id="use-case-6-sports-performance-analysis" class="slide level2">
<h2>Use Case 6 — Sports Performance Analysis</h2>
<p><strong>Scenario:</strong> Goals scored by two football strikers across 12 matches:</p>
<pre><code>Player A: 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 0, 1   → consistent scorer
Player B: 0, 0, 0, 5, 0, 0, 6, 0, 0, 4, 0, 3   → feast-or-famine scorer</code></pre>
<table class="caption-top">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Player A</th>
<th>Player B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total Goals</td>
<td>12</td>
<td>18</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>1.0</td>
<td>1.5</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>1.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Std Dev</td>
<td>0.74</td>
<td>2.23</td>
</tr>
</tbody>
</table>
<p><strong>Player B scores more total goals, but is highly unpredictable (high std dev). Player A is reliable.</strong></p>
<p>Different teams need different types based on their game strategy!</p>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-5-computing-with-python" class="title-slide slide level1 center">
<h1>Part 5: Computing with Python</h1>

</section>
<section id="python-setup-manual-calculation" class="slide level2">
<h2>Python Setup — Manual Calculation</h2>
<div class="sourceCode" id="cb48"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href=""></a><span class="co"># Computing all measures from scratch</span></span>
<span id="cb48-2"><a href=""></a></span>
<span id="cb48-3"><a href=""></a>data <span class="op">=</span> [<span class="dv">85</span>, <span class="dv">92</span>, <span class="dv">78</span>, <span class="dv">95</span>, <span class="dv">88</span>, <span class="dv">72</span>, <span class="dv">91</span>, <span class="dv">84</span>, <span class="dv">76</span>, <span class="dv">88</span>]</span>
<span id="cb48-4"><a href=""></a></span>
<span id="cb48-5"><a href=""></a><span class="co"># Mean</span></span>
<span id="cb48-6"><a href=""></a>n <span class="op">=</span> <span class="bu">len</span>(data)</span>
<span id="cb48-7"><a href=""></a>mean <span class="op">=</span> <span class="bu">sum</span>(data) <span class="op">/</span> n</span>
<span id="cb48-8"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Count: </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb48-9"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Mean: </span><span class="sc">{</span>mean<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb48-10"><a href=""></a></span>
<span id="cb48-11"><a href=""></a><span class="co"># Median</span></span>
<span id="cb48-12"><a href=""></a>sorted_data <span class="op">=</span> <span class="bu">sorted</span>(data)</span>
<span id="cb48-13"><a href=""></a><span class="cf">if</span> n <span class="op">%</span> <span class="dv">2</span> <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb48-14"><a href=""></a>    median <span class="op">=</span> sorted_data[n <span class="op">//</span> <span class="dv">2</span>]</span>
<span id="cb48-15"><a href=""></a><span class="cf">else</span>:</span>
<span id="cb48-16"><a href=""></a>    median <span class="op">=</span> (sorted_data[n <span class="op">//</span> <span class="dv">2</span> <span class="op">-</span> <span class="dv">1</span>] <span class="op">+</span> sorted_data[n <span class="op">//</span> <span class="dv">2</span>]) <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb48-17"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Median: </span><span class="sc">{</span>median<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb48-18"><a href=""></a></span>
<span id="cb48-19"><a href=""></a><span class="co"># Mode (manual)</span></span>
<span id="cb48-20"><a href=""></a><span class="im">from</span> collections <span class="im">import</span> Counter</span>
<span id="cb48-21"><a href=""></a>counts <span class="op">=</span> Counter(data)</span>
<span id="cb48-22"><a href=""></a>max_count <span class="op">=</span> <span class="bu">max</span>(counts.values())</span>
<span id="cb48-23"><a href=""></a>mode <span class="op">=</span> [k <span class="cf">for</span> k, v <span class="kw">in</span> counts.items() <span class="cf">if</span> v <span class="op">==</span> max_count]</span>
<span id="cb48-24"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Mode: </span><span class="sc">{</span>mode<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="python-range-variance-std-dev" class="slide level2">
<h2>Python — Range, Variance, Std Dev</h2>
<div class="sourceCode" id="cb49"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href=""></a>data <span class="op">=</span> [<span class="dv">85</span>, <span class="dv">92</span>, <span class="dv">78</span>, <span class="dv">95</span>, <span class="dv">88</span>, <span class="dv">72</span>, <span class="dv">91</span>, <span class="dv">84</span>, <span class="dv">76</span>, <span class="dv">88</span>]</span>
<span id="cb49-2"><a href=""></a>mean <span class="op">=</span> <span class="bu">sum</span>(data) <span class="op">/</span> <span class="bu">len</span>(data)</span>
<span id="cb49-3"><a href=""></a></span>
<span id="cb49-4"><a href=""></a><span class="co"># Range</span></span>
<span id="cb49-5"><a href=""></a>data_range <span class="op">=</span> <span class="bu">max</span>(data) <span class="op">-</span> <span class="bu">min</span>(data)</span>
<span id="cb49-6"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Min: </span><span class="sc">{</span><span class="bu">min</span>(data)<span class="sc">}</span><span class="ss">,  Max: </span><span class="sc">{</span><span class="bu">max</span>(data)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb49-7"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Range: </span><span class="sc">{</span>data_range<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb49-8"><a href=""></a></span>
<span id="cb49-9"><a href=""></a><span class="co"># Variance (sample — divide by n-1)</span></span>
<span id="cb49-10"><a href=""></a>deviations_squared <span class="op">=</span> [(x <span class="op">-</span> mean) <span class="op">**</span> <span class="dv">2</span> <span class="cf">for</span> x <span class="kw">in</span> data]</span>
<span id="cb49-11"><a href=""></a>variance <span class="op">=</span> <span class="bu">sum</span>(deviations_squared) <span class="op">/</span> (<span class="bu">len</span>(data) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb49-12"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Variance: </span><span class="sc">{</span>variance<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb49-13"><a href=""></a></span>
<span id="cb49-14"><a href=""></a><span class="co"># Standard Deviation</span></span>
<span id="cb49-15"><a href=""></a>std_dev <span class="op">=</span> variance <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb49-16"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Standard Deviation: </span><span class="sc">{</span>std_dev<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb49-17"><a href=""></a></span>
<span id="cb49-18"><a href=""></a><span class="co"># Show deviation table</span></span>
<span id="cb49-19"><a href=""></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">  x    |  x - mean  |  (x-mean)²"</span>)</span>
<span id="cb49-20"><a href=""></a><span class="bu">print</span>(<span class="st">"-"</span> <span class="op">*</span> <span class="dv">38</span>)</span>
<span id="cb49-21"><a href=""></a><span class="cf">for</span> x <span class="kw">in</span> data:</span>
<span id="cb49-22"><a href=""></a>    dev <span class="op">=</span> x <span class="op">-</span> mean</span>
<span id="cb49-23"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>x<span class="sc">}</span><span class="ss">  |   </span><span class="sc">{</span>dev<span class="sc">:+.2f}</span><span class="ss">    |  </span><span class="sc">{</span>dev<span class="op">**</span><span class="dv">2</span><span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="python-using-the-statistics-module" class="slide level2">
<h2>Python — Using the <code>statistics</code> Module</h2>
<div class="sourceCode" id="cb50"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href=""></a><span class="im">import</span> statistics</span>
<span id="cb50-2"><a href=""></a></span>
<span id="cb50-3"><a href=""></a>data <span class="op">=</span> [<span class="dv">85</span>, <span class="dv">92</span>, <span class="dv">78</span>, <span class="dv">95</span>, <span class="dv">88</span>, <span class="dv">72</span>, <span class="dv">91</span>, <span class="dv">84</span>, <span class="dv">76</span>, <span class="dv">88</span>]</span>
<span id="cb50-4"><a href=""></a></span>
<span id="cb50-5"><a href=""></a><span class="co"># Central Tendency</span></span>
<span id="cb50-6"><a href=""></a><span class="bu">print</span>(<span class="st">"=== Central Tendency ==="</span>)</span>
<span id="cb50-7"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Mean:   </span><span class="sc">{</span>statistics<span class="sc">.</span>mean(data)<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb50-8"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Median: </span><span class="sc">{</span>statistics<span class="sc">.</span>median(data)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb50-9"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Mode:   </span><span class="sc">{</span>statistics<span class="sc">.</span>mode(data)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb50-10"><a href=""></a></span>
<span id="cb50-11"><a href=""></a><span class="co"># Dispersion</span></span>
<span id="cb50-12"><a href=""></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">=== Dispersion ==="</span>)</span>
<span id="cb50-13"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Variance (sample):  </span><span class="sc">{</span>statistics<span class="sc">.</span>variance(data)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb50-14"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Std Dev (sample):   </span><span class="sc">{</span>statistics<span class="sc">.</span>stdev(data)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb50-15"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Range:              </span><span class="sc">{</span><span class="bu">max</span>(data) <span class="op">-</span> <span class="bu">min</span>(data)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb50-16"><a href=""></a></span>
<span id="cb50-17"><a href=""></a><span class="co"># Quantiles (Python 3.8+)</span></span>
<span id="cb50-18"><a href=""></a>q <span class="op">=</span> statistics.quantiles(data, n<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb50-19"><a href=""></a>iqr <span class="op">=</span> q[<span class="dv">2</span>] <span class="op">-</span> q[<span class="dv">0</span>]</span>
<span id="cb50-20"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Q1:  </span><span class="sc">{</span>q[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb50-21"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Q3:  </span><span class="sc">{</span>q[<span class="dv">2</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb50-22"><a href=""></a><span class="bu">print</span>(<span class="ss">f"IQR: </span><span class="sc">{</span>iqr<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="python-full-statistics-report-function" class="slide level2">
<h2>Python — Full Statistics Report Function</h2>
<div class="sourceCode" id="cb51"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href=""></a><span class="im">import</span> statistics</span>
<span id="cb51-2"><a href=""></a><span class="im">import</span> math</span>
<span id="cb51-3"><a href=""></a></span>
<span id="cb51-4"><a href=""></a><span class="kw">def</span> describe(data, label<span class="op">=</span><span class="st">"Dataset"</span>):</span>
<span id="cb51-5"><a href=""></a>    data <span class="op">=</span> <span class="bu">sorted</span>(data)</span>
<span id="cb51-6"><a href=""></a>    n <span class="op">=</span> <span class="bu">len</span>(data)</span>
<span id="cb51-7"><a href=""></a>    mean <span class="op">=</span> statistics.mean(data)</span>
<span id="cb51-8"><a href=""></a>    med <span class="op">=</span> statistics.median(data)</span>
<span id="cb51-9"><a href=""></a>    <span class="cf">try</span>:</span>
<span id="cb51-10"><a href=""></a>        mode_val <span class="op">=</span> statistics.mode(data)</span>
<span id="cb51-11"><a href=""></a>    <span class="cf">except</span>:</span>
<span id="cb51-12"><a href=""></a>        mode_val <span class="op">=</span> <span class="st">"None (all unique)"</span></span>
<span id="cb51-13"><a href=""></a></span>
<span id="cb51-14"><a href=""></a>    variance <span class="op">=</span> statistics.variance(data)</span>
<span id="cb51-15"><a href=""></a>    std_dev <span class="op">=</span> statistics.stdev(data)</span>
<span id="cb51-16"><a href=""></a>    q <span class="op">=</span> statistics.quantiles(data, n<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb51-17"><a href=""></a>    iqr <span class="op">=</span> q[<span class="dv">2</span>] <span class="op">-</span> q[<span class="dv">0</span>]</span>
<span id="cb51-18"><a href=""></a>    lower_fence <span class="op">=</span> q[<span class="dv">0</span>] <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb51-19"><a href=""></a>    upper_fence <span class="op">=</span> q[<span class="dv">2</span>] <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb51-20"><a href=""></a>    outliers <span class="op">=</span> [x <span class="cf">for</span> x <span class="kw">in</span> data <span class="cf">if</span> x <span class="op">&lt;</span> lower_fence <span class="kw">or</span> x <span class="op">&gt;</span> upper_fence]</span>
<span id="cb51-21"><a href=""></a></span>
<span id="cb51-22"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="st">'='</span><span class="op">*</span><span class="dv">45</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-23"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Statistics Report: </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-24"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'='</span><span class="op">*</span><span class="dv">45</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-25"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Count:      </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-26"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Min / Max:  </span><span class="sc">{</span>data[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> / </span><span class="sc">{</span>data[<span class="op">-</span><span class="dv">1</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-27"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Range:      </span><span class="sc">{</span>data[<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> data[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-28"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  ──────────────────────────────────────"</span>)</span>
<span id="cb51-29"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Mean:       </span><span class="sc">{</span>mean<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb51-30"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Median:     </span><span class="sc">{</span>med<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-31"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Mode:       </span><span class="sc">{</span>mode_val<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-32"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  ──────────────────────────────────────"</span>)</span>
<span id="cb51-33"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Variance:   </span><span class="sc">{</span>variance<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb51-34"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Std Dev:    </span><span class="sc">{</span>std_dev<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb51-35"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Q1:         </span><span class="sc">{</span>q[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-36"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Q3:         </span><span class="sc">{</span>q[<span class="dv">2</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-37"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  IQR:        </span><span class="sc">{</span>iqr<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-38"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Fences:     [</span><span class="sc">{</span>lower_fence<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>upper_fence<span class="sc">:.2f}</span><span class="ss">]"</span>)</span>
<span id="cb51-39"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"  Outliers:   </span><span class="sc">{</span>outliers <span class="cf">if</span> outliers <span class="cf">else</span> <span class="st">'None'</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-40"><a href=""></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'='</span><span class="op">*</span><span class="dv">45</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-41"><a href=""></a></span>
<span id="cb51-42"><a href=""></a><span class="co"># Test it!</span></span>
<span id="cb51-43"><a href=""></a>exam_scores <span class="op">=</span> [<span class="dv">55</span>, <span class="dv">62</span>, <span class="dv">70</span>, <span class="dv">73</span>, <span class="dv">75</span>, <span class="dv">78</span>, <span class="dv">80</span>, <span class="dv">82</span>, <span class="dv">82</span>, <span class="dv">85</span>, <span class="dv">88</span>, <span class="dv">90</span>, <span class="dv">92</span>, <span class="dv">95</span>, <span class="dv">45</span>]</span>
<span id="cb51-44"><a href=""></a>describe(exam_scores, <span class="st">"Exam Scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="python-comparing-two-datasets" class="slide level2">
<h2>Python — Comparing Two Datasets</h2>
<div class="sourceCode" id="cb52"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href=""></a><span class="im">import</span> statistics</span>
<span id="cb52-2"><a href=""></a></span>
<span id="cb52-3"><a href=""></a>fund_a <span class="op">=</span> [<span class="fl">2.1</span>, <span class="fl">1.8</span>, <span class="fl">2.3</span>, <span class="fl">2.0</span>, <span class="fl">1.9</span>, <span class="fl">2.2</span>, <span class="fl">2.0</span>, <span class="fl">1.7</span>, <span class="fl">2.1</span>, <span class="fl">2.4</span>]</span>
<span id="cb52-4"><a href=""></a>fund_b <span class="op">=</span> [<span class="fl">5.2</span>, <span class="op">-</span><span class="fl">3.1</span>, <span class="fl">8.4</span>, <span class="op">-</span><span class="fl">2.0</span>, <span class="fl">6.7</span>, <span class="op">-</span><span class="fl">1.5</span>, <span class="fl">9.1</span>, <span class="op">-</span><span class="fl">4.2</span>, <span class="fl">7.3</span>, <span class="fl">1.1</span>]</span>
<span id="cb52-5"><a href=""></a></span>
<span id="cb52-6"><a href=""></a><span class="bu">print</span>(<span class="st">"=== Investment Fund Comparison ===</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb52-7"><a href=""></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Metric'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Fund A'</span><span class="sc">:&gt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Fund B'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="cb52-8"><a href=""></a><span class="bu">print</span>(<span class="st">"-"</span> <span class="op">*</span> <span class="dv">42</span>)</span>
<span id="cb52-9"><a href=""></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Mean Return'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span>statistics<span class="sc">.</span>mean(fund_a)<span class="sc">:&gt;9.2f}</span><span class="ss">% </span><span class="sc">{</span>statistics<span class="sc">.</span>mean(fund_b)<span class="sc">:&gt;9.2f}</span><span class="ss">%"</span>)</span>
<span id="cb52-10"><a href=""></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Median Return'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span>statistics<span class="sc">.</span>median(fund_a)<span class="sc">:&gt;9.2f}</span><span class="ss">% </span><span class="sc">{</span>statistics<span class="sc">.</span>median(fund_b)<span class="sc">:&gt;9.2f}</span><span class="ss">%"</span>)</span>
<span id="cb52-11"><a href=""></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Std Dev (Risk)'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span>statistics<span class="sc">.</span>stdev(fund_a)<span class="sc">:&gt;9.2f}</span><span class="ss">% </span><span class="sc">{</span>statistics<span class="sc">.</span>stdev(fund_b)<span class="sc">:&gt;9.2f}</span><span class="ss">%"</span>)</span>
<span id="cb52-12"><a href=""></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Min Return'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span><span class="bu">min</span>(fund_a)<span class="sc">:&gt;9.2f}</span><span class="ss">% </span><span class="sc">{</span><span class="bu">min</span>(fund_b)<span class="sc">:&gt;9.2f}</span><span class="ss">%"</span>)</span>
<span id="cb52-13"><a href=""></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Max Return'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span><span class="bu">max</span>(fund_a)<span class="sc">:&gt;9.2f}</span><span class="ss">% </span><span class="sc">{</span><span class="bu">max</span>(fund_b)<span class="sc">:&gt;9.2f}</span><span class="ss">%"</span>)</span>
<span id="cb52-14"><a href=""></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Range'</span><span class="sc">:&lt;20}</span><span class="ss"> </span><span class="sc">{</span><span class="bu">max</span>(fund_a)<span class="op">-</span><span class="bu">min</span>(fund_a)<span class="sc">:&gt;9.2f}</span><span class="ss">% </span><span class="sc">{</span><span class="bu">max</span>(fund_b)<span class="op">-</span><span class="bu">min</span>(fund_b)<span class="sc">:&gt;9.2f}</span><span class="ss">%"</span>)</span>
<span id="cb52-15"><a href=""></a></span>
<span id="cb52-16"><a href=""></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Conclusion:"</span>)</span>
<span id="cb52-17"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Fund B has higher mean (</span><span class="sc">{</span>statistics<span class="sc">.</span>mean(fund_b)<span class="sc">:.2f}</span><span class="ss">%) but"</span>,</span>
<span id="cb52-18"><a href=""></a>      <span class="ss">f"</span><span class="sc">{</span>statistics<span class="sc">.</span>stdev(fund_b)<span class="op">/</span>statistics<span class="sc">.</span>stdev(fund_a)<span class="sc">:.0f}</span><span class="ss">x more risk!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="final-challenge-real-dataset-analysis" class="slide level2">
<h2>Final Challenge — Real Dataset Analysis</h2>
<p><strong>Your task:</strong> Analyze this real sales dataset and produce a full report.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href=""></a><span class="im">import</span> statistics</span>
<span id="cb53-2"><a href=""></a></span>
<span id="cb53-3"><a href=""></a><span class="co"># Monthly sales ($) for 3 products over 12 months</span></span>
<span id="cb53-4"><a href=""></a>product_A <span class="op">=</span> [<span class="dv">1200</span>, <span class="dv">1350</span>, <span class="dv">1100</span>, <span class="dv">1450</span>, <span class="dv">1300</span>, <span class="dv">1250</span>,</span>
<span id="cb53-5"><a href=""></a>             <span class="dv">1380</span>, <span class="dv">1420</span>, <span class="dv">1280</span>, <span class="dv">1310</span>, <span class="dv">1190</span>, <span class="dv">1360</span>]</span>
<span id="cb53-6"><a href=""></a></span>
<span id="cb53-7"><a href=""></a>product_B <span class="op">=</span> [<span class="dv">800</span>, <span class="dv">2100</span>, <span class="dv">650</span>, <span class="dv">1900</span>, <span class="dv">750</span>, <span class="dv">2300</span>,</span>
<span id="cb53-8"><a href=""></a>             <span class="dv">900</span>, <span class="dv">1800</span>, <span class="dv">700</span>, <span class="dv">2000</span>, <span class="dv">850</span>, <span class="dv">2200</span>]</span>
<span id="cb53-9"><a href=""></a></span>
<span id="cb53-10"><a href=""></a>product_C <span class="op">=</span> [<span class="dv">500</span>, <span class="dv">520</span>, <span class="dv">510</span>, <span class="dv">490</span>, <span class="dv">5000</span>, <span class="dv">505</span>,</span>
<span id="cb53-11"><a href=""></a>             <span class="dv">495</span>, <span class="dv">515</span>, <span class="dv">500</span>, <span class="dv">510</span>, <span class="dv">498</span>, <span class="dv">502</span>]</span>
<span id="cb53-12"><a href=""></a></span>
<span id="cb53-13"><a href=""></a><span class="co"># ============================================</span></span>
<span id="cb53-14"><a href=""></a><span class="co"># Your tasks:</span></span>
<span id="cb53-15"><a href=""></a><span class="co"># 1. For EACH product, calculate and print:</span></span>
<span id="cb53-16"><a href=""></a><span class="co">#    - Mean, Median, Mode</span></span>
<span id="cb53-17"><a href=""></a><span class="co">#    - Range, Std Dev, IQR</span></span>
<span id="cb53-18"><a href=""></a><span class="co">#    - Detect outliers using IQR method</span></span>
<span id="cb53-19"><a href=""></a><span class="co">#</span></span>
<span id="cb53-20"><a href=""></a><span class="co"># 2. Answer these questions in your code comments:</span></span>
<span id="cb53-21"><a href=""></a><span class="co">#    - Which product has the most consistent sales?</span></span>
<span id="cb53-22"><a href=""></a><span class="co">#    - Which product has an obvious outlier? What month?</span></span>
<span id="cb53-23"><a href=""></a><span class="co">#    - Which product is most predictable for budgeting?</span></span>
<span id="cb53-24"><a href=""></a><span class="co">#    - Would you use mean or median for each product? Why?</span></span>
<span id="cb53-25"><a href=""></a><span class="co"># ============================================</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>💡 Hints</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Call your <code>describe()</code> function on each product list</li>
<li>A high std dev relative to mean = unpredictable</li>
<li>An outlier might be a holiday promotion, data entry error, or one-time event</li>
</ul>
</div>
</div>
</div>
</section>
<section id="summary-descriptive-statistics" class="slide level2">
<h2>Summary: Descriptive Statistics</h2>
<p><strong>What you’ve learned today:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 29%">
<col style="width: 26%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Measures</th>
<th>Best Used When</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Central Tendency</strong></td>
<td>Mean, Median, Mode</td>
<td>Symmetric / Skewed / Categorical</td>
</tr>
<tr class="even">
<td><strong>Dispersion</strong></td>
<td>Range, Variance, Std Dev, IQR</td>
<td>Quick view / Precise / Outlier-robust</td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🎯 Key Takeaways</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Mean</strong> = fair average, sensitive to outliers</li>
<li><strong>Median</strong> = middle value, robust to outliers</li>
<li><strong>Mode</strong> = most common, works for categories</li>
<li><strong>Std Dev</strong> = typical distance from mean, same units as data</li>
<li><strong>IQR</strong> = spread of middle 50%, unaffected by outliers</li>
<li>Always <strong>pair</strong> central tendency with dispersion — one without the other is incomplete!</li>
<li>When in doubt: check for outliers first, then choose your measures</li>
</ul>
</div>
</div>
</div>
</section>
<section id="common-mistakes-to-avoid" class="slide level2">
<h2>Common Mistakes to Avoid</h2>
<pre><code>❌ Reporting only the mean without any dispersion measure
   → The mean of 75 means nothing without knowing the spread!

❌ Using mean with heavily skewed or outlier-affected data
   → Use median instead for income, house prices, wait times

❌ Confusing variance and standard deviation units
   → Variance is in squared units; std dev is in original units

❌ Forgetting to sort before finding the median
   → Median of unsorted data is meaningless!

❌ Assuming mode always exists
   → If all values are unique, there is no mode

❌ Ignoring outliers without investigating them
   → Outliers are often the most interesting and important data points!</code></pre>
</section>
<section id="quick-reference-card" class="slide level2">
<h2>Quick Reference Card</h2>
<p><span class="math display">\[\bar{x} = \frac{\sum x_i}{n} \qquad \text{(Mean)}\]</span></p>
<p><span class="math display">\[\text{Median} = \text{middle value of sorted data}\]</span></p>
<p><span class="math display">\[s^2 = \frac{\sum(x_i - \bar{x})^2}{n-1} \qquad \text{(Variance)}\]</span></p>
<p><span class="math display">\[s = \sqrt{s^2} \qquad \text{(Standard Deviation)}\]</span></p>
<p><span class="math display">\[\text{IQR} = Q_3 - Q_1\]</span></p>
<p><span class="math display">\[\text{Outlier fences: } Q_1 - 1.5 \times \text{IQR} \quad \text{and} \quad Q_3 + 1.5 \times \text{IQR}\]</span></p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="session910_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="session910_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="session910_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="session910_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="session910_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="session910_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="session910_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="session910_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="session910_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="session910_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>